### ISSUE TITLE
bluedog_Titan_Transtage has now hypergolic engine but tank is still LFO and no switcher

### ISSUE THREAD

**Issue by Gordon-Dry** [Clamp-o-Tron/KSP-More-Fuels#15]
As title.
See
![screenshot_2020-10-02--23-13-35](https://user-images.githubusercontent.com/29145213/94970505-175edb80-0505-11eb-9a92-3c708e50c42d.jpg)

**Comment by Gordon-Dry** [comment]
Also interesting:
![screenshot_2020-10-02--23-16-01](https://user-images.githubusercontent.com/29145213/94970612-555bff80-0505-11eb-8f93-6fcfc90cf607.jpg)

**Comment by Clamp-o-Tron** [comment]
I know what's up. Will push later tonight.
